name: Deploy MkDocs Blog

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs
        run: pip install mkdocs

      - name: Build static site
        run: mkdocs build

      - name: Upload site files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
