name: Deploy MkDocs Blog
on:
  push:
    branches: [ main ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
      - name: 安装Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: 安装MkDocs和主题
        run: pip install mkdocs mkdocs-material
      - name: 编译博客并推送至gh-pages分支
        run: mkdocs gh-deploy --force 
